/*! This file was generated by vite-i18n-gen-resources-type check https://github.com/CRMChatReactComponent/vite-i18n-gen-resources-type. Please do not modify. */
export interface I18nResourceInterface {
  translation: {
    nameFieldName: "名称:";
    nameFieldPlaceholder: "请输入您的中文名称";
  };
  common: {
    deleteCurrentIcon: "删除当前图标";
    deleteCurrentColor: "删除当前颜色";
    changeBackgroundColor: "修改背景色";
    changeTitle: "修改标题";
    presets: "预设";
    deepColor: "深色";
    mildColor: "柔和";
    lightColor: "浅色";
    delete: "删除";
    deleteSuccessfully: "删除成功!";
    dangerOperation: "危险操作";
    confirmToDelete: "确定删除吗？该操作无法回退！";
    cancelText: "取消";
    confirmText: "确认";
  };
}
